-- CreateTable
CREATE TABLE "FACULTY" (
    "facultyID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "facultyName" TEXT NOT NULL,
    "facultyCode" TEXT NOT NULL,
    "locationDesc" TEXT
);

-- CreateTable
CREATE TABLE "CAMPUS_USER" (
    "campusUserID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "facultyID" INTEGER NOT NULL,
    "fullName" TEXT NOT NULL,
    "userType" TEXT NOT NULL,
    "studentNo" TEXT,
    "staffNo" TEXT,
    "email" TEXT NOT NULL,
    "phoneNum" TEXT,
    "status" TEXT NOT NULL,
    CONSTRAINT "CAMPUS_USER_facultyID_fkey" FOREIGN KEY ("facultyID") REFERENCES "FACULTY" ("facultyID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PARKING_ZONE" (
    "zoneID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "facultyID" INTEGER NOT NULL,
    "zoneName" TEXT NOT NULL,
    "zoneType" TEXT NOT NULL,
    "capacity" INTEGER NOT NULL,
    "locationDesc" TEXT,
    CONSTRAINT "PARKING_ZONE_facultyID_fkey" FOREIGN KEY ("facultyID") REFERENCES "FACULTY" ("facultyID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PARKING_LOT" (
    "lotID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "zoneID" INTEGER NOT NULL,
    "lotNumber" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "isDisabledFriendly" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "PARKING_LOT_zoneID_fkey" FOREIGN KEY ("zoneID") REFERENCES "PARKING_ZONE" ("zoneID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "VEHICLE" (
    "vehicleID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "campusUserID" INTEGER,
    "plateNum" TEXT NOT NULL,
    "vehicleType" TEXT NOT NULL,
    "ownerName" TEXT NOT NULL,
    "ownerType" TEXT NOT NULL,
    "contactNum" TEXT,
    CONSTRAINT "VEHICLE_campusUserID_fkey" FOREIGN KEY ("campusUserID") REFERENCES "CAMPUS_USER" ("campusUserID") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PERMIT" (
    "permitID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "vehicleID" INTEGER NOT NULL,
    "zoneID" INTEGER NOT NULL,
    "permitType" TEXT NOT NULL,
    "startDate" DATETIME NOT NULL,
    "endDate" DATETIME NOT NULL,
    "status" TEXT NOT NULL,
    CONSTRAINT "PERMIT_vehicleID_fkey" FOREIGN KEY ("vehicleID") REFERENCES "VEHICLE" ("vehicleID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PERMIT_zoneID_fkey" FOREIGN KEY ("zoneID") REFERENCES "PARKING_ZONE" ("zoneID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "RESERVATION" (
    "reservationID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "facultyID" INTEGER NOT NULL,
    "zoneID" INTEGER NOT NULL,
    "lotID" INTEGER NOT NULL,
    "vehicleID" INTEGER NOT NULL,
    "reservationDate" DATETIME NOT NULL,
    "startTime" DATETIME NOT NULL,
    "endTime" DATETIME NOT NULL,
    "createdDateTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "status" TEXT NOT NULL,
    "userType" TEXT NOT NULL,
    "proofCode" TEXT NOT NULL,
    CONSTRAINT "RESERVATION_facultyID_fkey" FOREIGN KEY ("facultyID") REFERENCES "FACULTY" ("facultyID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "RESERVATION_zoneID_fkey" FOREIGN KEY ("zoneID") REFERENCES "PARKING_ZONE" ("zoneID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "RESERVATION_lotID_fkey" FOREIGN KEY ("lotID") REFERENCES "PARKING_LOT" ("lotID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "RESERVATION_vehicleID_fkey" FOREIGN KEY ("vehicleID") REFERENCES "VEHICLE" ("vehicleID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PARKING_SESSION" (
    "sessionID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "lotID" INTEGER NOT NULL,
    "vehicleID" INTEGER NOT NULL,
    "reservationID" INTEGER,
    "entryTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "exitTime" DATETIME,
    "sessionType" TEXT NOT NULL,
    "isViolation" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "PARKING_SESSION_lotID_fkey" FOREIGN KEY ("lotID") REFERENCES "PARKING_LOT" ("lotID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PARKING_SESSION_vehicleID_fkey" FOREIGN KEY ("vehicleID") REFERENCES "VEHICLE" ("vehicleID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PARKING_SESSION_reservationID_fkey" FOREIGN KEY ("reservationID") REFERENCES "RESERVATION" ("reservationID") ON DELETE SET NULL ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "ADMIN" (
    "adminID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "adminName" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phoneNum" TEXT,
    "role" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "FINE" (
    "fineID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "sessionID" INTEGER NOT NULL,
    "adminID" INTEGER NOT NULL,
    "issuedDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "fineType" TEXT NOT NULL,
    "amount" REAL NOT NULL,
    "status" TEXT NOT NULL,
    "remarks" TEXT,
    CONSTRAINT "FINE_sessionID_fkey" FOREIGN KEY ("sessionID") REFERENCES "PARKING_SESSION" ("sessionID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "FINE_adminID_fkey" FOREIGN KEY ("adminID") REFERENCES "ADMIN" ("adminID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PAYMENT" (
    "paymentID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "fineID" INTEGER NOT NULL,
    "adminID" INTEGER NOT NULL,
    "paymentDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "amountPaid" REAL NOT NULL,
    "paymentMethod" TEXT NOT NULL,
    "receiptNum" TEXT,
    "gatewayRef" TEXT,
    CONSTRAINT "PAYMENT_fineID_fkey" FOREIGN KEY ("fineID") REFERENCES "FINE" ("fineID") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "PAYMENT_adminID_fkey" FOREIGN KEY ("adminID") REFERENCES "ADMIN" ("adminID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "FACULTY_facultyCode_key" ON "FACULTY"("facultyCode");

-- CreateIndex
CREATE UNIQUE INDEX "CAMPUS_USER_studentNo_key" ON "CAMPUS_USER"("studentNo");

-- CreateIndex
CREATE UNIQUE INDEX "CAMPUS_USER_staffNo_key" ON "CAMPUS_USER"("staffNo");

-- CreateIndex
CREATE UNIQUE INDEX "CAMPUS_USER_email_key" ON "CAMPUS_USER"("email");

-- CreateIndex
CREATE UNIQUE INDEX "VEHICLE_plateNum_key" ON "VEHICLE"("plateNum");

-- CreateIndex
CREATE UNIQUE INDEX "RESERVATION_proofCode_key" ON "RESERVATION"("proofCode");

-- CreateIndex
CREATE UNIQUE INDEX "ADMIN_username_key" ON "ADMIN"("username");

-- CreateIndex
CREATE UNIQUE INDEX "ADMIN_email_key" ON "ADMIN"("email");
